concertmon:
    build: .
    container_name: concertmon
    environment: 
      LASTFM_PAGES_TO_FETCH: 20
      LASTFM_USERNAME: "Get from https://www.last.fm/api/account/create"
      LASTFM_API_KEY: "Get from https://www.last.fm/api/account/create"
      EMAIL: "Your email to send to bandsintown API (they ask for it)"
      # Comma-separated list of countries to monitor
      COUNTRIES: "Germany,Deutschland"
      # Comma-separated list of cities in those countries to monitor
      CITIES: "Munich,München"
    volumes: 
      - .:/concertmon
    command: python3 -u concertmon/monitor.py